# Generated by Django 5.2 on 2025-07-14 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='expiration_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
