# Generated by Django 5.2 on 2025-11-11 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_folder_options_folder_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='contracts.folder'),
        ),
    ]
