FROM python:3.12-alpine

ENV PYTHONPYCACHEPREFIX=/dev/null

RUN apt update && apt add git gettext 

WORKDIR /code

COPY requirements.txt /code/requirements.txt

RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

CMD ["sh", "./entrypoint.sh"]